#!/bin/bash
cd ./evm/evm1/evm1

g++ -std=c++11 -O0 evm2.cpp  -o  evm2_O0.out
g++ -std=c++11 -O1 evm2.cpp  -o  evm2_O1.out
g++ -std=c++11 -O2 evm2.cpp  -o  evm2_O2.out
g++ -std=c++11 -O3 evm2.cpp  -o  evm2_O3.out
g++ -std=c++11 -Os evm2.cpp  -o  evm2_Os.out
g++ -std=c++11 -Ofast evm2.cpp  -o  evm2_Ofast.out
g++ -std=c++11 -Og evm2.cpp  -o  evm2_Og.out
echo value of N: $1
echo O0 mode
time ./evm2_O0.out $1
echo O1 mode
time ./evm2_O1.out $1
echo O2 mode
time ./evm2_O2.out $1
echo O3 mode
time ./evm2_O3.out $1
echo Os mode
time ./evm2_Os.out $1
echo Ofast mode
time ./evm2_Ofast.out $1
echo Og mode
time ./evm2_Og.out $1


